<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mf_teaser"
 *
 * Auto generated by Extension Builder 2017-05-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Megafry Teaser-Element',
    'description' => 'Teaser-Element using fluid_styled_content and boostrap',
    'category' => 'plugin',
    'author' => 'Eugen Fritz',
    'author_email' => 'eugene.fritz@hotmail.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
